### ISSUE TITLE
如果同一台服务器需要两个以上域名并且在不同的阿里云上是否支持？

### ISSUE THREAD

**Issue by DreamPWJ** [tengattack/certbot-dns-aliyun#14]
建不同的credentials.ini ？

**Comment by DreamPWJ** [comment]
并且 certonly 同时生成多个证书好像不行，测试只生成了最后一个  certbot certonly -a certbot-dns-aliyun:dns-aliyun \
    --certbot-dns-aliyun:dns-aliyun-credentials /my/credentials.ini \
    -d health.admin-api.antaikeji.top -d health.third-platform.antaikeji.top \
    -d "*.antaikeji.top"

**Comment by DreamPWJ** [comment]
Do you want to expand and replace this existing certificate with the new
certificate?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(E)xpand/(C)ancel: E
这个提示能否默认实现全自动化？

**Comment by DreamPWJ** [comment]
certbot: error: argument -a/--authenticator: expected one argument    执行报错了

**Comment by DreamPWJ** [comment]
还有  Plugin legacy name certbot-dns-aliyun:dns-aliyun may be removed in a future version. Please use dns-aliyun instead.
 这个提示能否去掉， 看着好别扭，还以为执行出错了呢

**Comment by tengattack** [comment]
目前同时生成可能不太行，如果是多次签不同服务商的话可以

**Comment by DreamPWJ** [comment]
> 目前同时生成可能不太行，如果是多次签不同服务商的话可以
用一个服务商 多个域名同时生成支持吗？
