### ISSUE TITLE
阿里云API是否有变动？

### ISSUE THREAD

**Issue by lllyyylll2** [tengattack/certbot-dns-aliyun#2]
已在阿里云控制台上给用户分配了AliyunDomainFullAccess权限，任然报一下错误：
AliError: User not authorized to operate on the specified resource, or this API doesn't support RAM

**Comment by tengattack** [comment]
应该需要 `AliyunDNSFullAccess` 权限

**Comment by lllyyylll2** [comment]
嗯 ， 修改权限后就OK了。 多谢。
