### ISSUE TITLE
证书到期后，renew遇到问题

### ISSUE THREAD

**Issue by lllyyylll2** [tengattack/certbot-dns-aliyun#3]
证书到期后，运行 certbot-auto renew 时遇到一下错误：
> Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',)
Attempting to renew cert (test.com) from /etc/letsencrypt/renewal/test.com.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',). Skipping.

需要做额外设置吗？

**Comment by tengattack** [comment]
看起来是 manual 插件的问题？和这个插件应该没有关系，建议重新生成新的证书试试~

然后试试 `renew --dry-run`

**Comment by lllyyylll2** [comment]
哦 查到问题了， renew的时候加上插件参数就好了。
`certbot-auto renew  -a certbot-dns-aliyun:dns-aliyun --certbot-dns-aliyun:dns-aliyun-credentials ./credentials.ini`

**Comment by tengattack** [comment]
这个插件参数应该可以被配置在配置文件里的

**Comment by tengattack** [comment]
在 `/etc/letsencrypt/renewal/test.com.conf` 下应该有个 `[renewalparams]` 配置了：

```
authenticator = certbot-dns-aliyun:dns-aliyun
certbot_dns_aliyun:dns_aliyun_credentials = /etc/letsencrypt/credentials.ini
```

**Comment by lllyyylll2** [comment]
我看了下，没有自动生成该参数。

**Comment by tengattack** [comment]
应该也可以自己手动配置这两个参数
