### ISSUE TITLE
直接使用pip install certbot-dns-aliyun后，credentials.ini在哪个路径下？

### ISSUE THREAD

**Issue by Power-tile** [tengattack/certbot-dns-aliyun#8]
如题，直接使用```pip install certbot-dns-aliyun```后没有找到```credentials.ini```。这个文件需要自己在哪个文件夹下创建吗？
[这篇教程](https://www.cnblogs.com/bbling/p/12807642.html) 先配置虚拟环境```venv```之后再```pip install```，即可让```credentials.ini```在指定环境的文件夹中。如果不创建```venv```应该在哪里找到/创建```credentials.ini```呢？

**Comment by tengattack** [comment]
`credentials.ini` 文件没有默认创建，可以创建在你想要的地方，一般我会创建在 `/etc/letsencrypt` 下，然后通过参数指定：
```sh
--certbot-dns-aliyun:dns-aliyun-credentials /etc/letsencrypt/credentials.ini
```

**Comment by Power-tile** [comment]
谢谢！麻烦了
