### ISSUE TITLE
certbot找不到--certbot-dns-aliyun:dns-aliyun-credentials参数

### ISSUE THREAD

**Issue by Power-tile** [tengattack/certbot-dns-aliyun#9]
```bash
certbot certonly -a certbot-dns-aliyun:dns-aliyun \
    --certbot-dns-aliyun:dns-aliyun-credentials /path/to/credentials.ini \
    -d example.com \
    -d "*.example.com"
```
运行后报错：找不到该参数
![image](https://user-images.githubusercontent.com/44731563/105953938-fb340b00-60ae-11eb-87d7-6e99f0244907.png)

**Comment by tengattack** [comment]
是不是包没有安装正确，certbot 会启动 venv 吗

**Comment by Power-tile** [comment]
我没有使用venv安装certbot-dns-aliyun 是直接```pip install certbot-dns-aliyun```的

**Comment by tengattack** [comment]
certbot 也是 pip 一起安装的吗？certbot 现在是啥版本呢可以看看吗

**Comment by Power-tile** [comment]
啊 certbot是用官方推荐的snapd装的 版本号1.1.0

**Comment by tengattack** [comment]
snapd 装的啊，是不是走的不是系统 pip 安装的目录，我稍晚看看~

**Comment by Power-tile** [comment]
ok thanks
我把certbot + snapd全部卸载了重新用pip装了一遍 显示装在```/usr/local/lib/python3.6/dist-packages/certbot```目录里 但是这个文件夹下只有一堆.py文件 没有certbot可执行文件没法直接```certbot --version```

**Comment by tengattack** [comment]
是不是得看下安装到哪里去了

**Comment by Power-tile** [comment]
应该就是这个地方吧...? 重新运行了一遍pip install certbot告诉我的路径就在这里
![image](https://user-images.githubusercontent.com/44731563/105967427-c92ba480-60c0-11eb-96c6-b1a77a8d9700.png)
而且pip安装的应该是可以直接import的module...? 所以没有可执行文件？

**Comment by tengattack** [comment]
这样，是否考虑用系统的包管理安装，或者使用 certbot-auto 的形式？

**Comment by Power-tile** [comment]
我屈服了hhh 我用venv装 就会在./venv/bin/下面得到certbot的可执行文件 就可以运行了
运行过程没啥问题 询问了我的邮箱、同意条款、同意他们给我发信息，我分别填了邮箱，Y，N

但是返回的时候报了一个exception:
Encountered exception during recovery: certbot.errors.PluginError: Unable to determine zone identifier for <我的域名>.com using zone names: ['<我的域名>.com', 'com']
Unable to determine zone identifier for <我的域名>.com using zone names: ['<我的域名>.com', 'com']

我个人感觉这可能和我的域名是a-b.com的格式有关...? 我在执行certbot的时候 -d "my-domain.com" -d "*.my-domain.com"的时候都加了双引号 而且运行到后面返回的时候才出错的 这是不是plugin在域名字符串分离的时候的问题呀（

**Comment by tengattack** [comment]
plugin 里分离应该不会有这个问题，晚点我一起看下使用 a-b 的形式的时候，这块会不会有什么问题

**Comment by Power-tile** [comment]
ok thanks

**Comment by Power-tile** [comment]
@tengattack 我简单看了一下 这个错误应该是[这一行](https://github.com/tengattack/certbot-dns-aliyun/blob/498c1103a84ab26830e7b0e4218432431bffcb59/certbot_dns_aliyun/alidns.py#L54)报出来的 但是我不确定怎么对这个项目做调试/怎么搭调试环境 请问你可以试试在这里打个断点调试一下嘛 谢谢

**Comment by tengattack** [comment]
> @tengattack 我简单看了一下 这个错误应该是[这一行](https://github.com/tengattack/certbot-dns-aliyun/blob/498c1103a84ab26830e7b0e4218432431bffcb59/certbot_dns_aliyun/alidns.py#L54)报出来的 但是我不确定怎么对这个项目做调试/怎么搭调试环境 请问你可以试试在这里打个断点调试一下嘛 谢谢

@Power-tile 您方便看下你创建的 RAM 子账号里有相关权限吗，目前的逻辑是搜索您传入的域名，应该总是可以找到才对

**Comment by Power-tile** [comment]
！啊 它好了 我的RAM子账号原先属于的工作组没有AliyunDNSFullAccess权限，只有该帐号自己有，我把工作组的权限加上就好了

**Comment by tengattack** [comment]
snap 上也发布了：

```sh
sudo snap install certbot-dns-aliyun
sudo snap set certbot trust-plugin-with-root=ok
sudo snap connect certbot:plugin certbot-dns-aliyun
/snap/bin/certbot plugins
```

plugins 看是有了
